name: Build Python Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CFLAGS: -O0

jobs:
  build-darwin-arm:
    runs-on: macos-15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install lxml
          pip3 install jinja2
          pip3 install black
          pip3 install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller xml2st.py --add-data plcopen:plcopen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-arm-executable
          path: dist/xml2st

  build-darwin-x64:
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install lxml
          pip3 install jinja2
          pip3 install black
          pip3 install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller xml2st.py --add-data plcopen:plcopen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-x64-executable
          path: dist/xml2st

  build-linux-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up linux environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv binutils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install lxml
          pip3 install jinja2
          pip3 install black
          pip3 install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller xml2st.py -F --add-data plcopen:plcopen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-executable
          path: dist/xml2st

  build-linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up linux environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv binutils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install lxml
          pip3 install jinja2
          pip3 install black
          pip3 install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller xml2st.py -F --add-data plcopen:plcopen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64-executable
          path: dist/xml2st

  build-windows-arm:
    runs-on: windows-11-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml==5.0.0
          pip install jinja2
          pip install black
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller xml2st.py -F --add-data plcopen:plcopen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm-executable
          path: dist

  build-windows-x64:
    runs-on: windows-2025
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
          pip install jinja2
          pip install black
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller xml2st.py -F --add-data plcopen:plcopen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-executable
          path: dist
